security.jwt.token.secret-key: my-secret-key

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fakebook
    username: backend
    password: backend
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update

#
#spring.datasource.url=jdbc:postgresql://localhost:5432/fakebook
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## This will create table automatically in your database
#spring.jpa.hibernate.ddl-auto=update
#
#jwt.header=Authorization
#security.jwt.token.secret-key=my-very-secret-key